name: 'Zigbee Temp Sensor and Child Thermostat Mc-(OLD)'
packageKey: 'Zigbee_Temp_Humidity_Sensor_v5'
description: 'Supported Devices: https://github.com/Mariano-Github/Edge-Drivers-Beta/blob/main/zigbee-temp-humidity-child-thermostat/fingerprints.yml'
permissions:
  zigbee: {}
